version: 2

aliases:
  - &setup-artifacts
    name: Initial Setup
    command: |
      mkdir -p ~/podlove-web-player

  # yarn helpers
  - &yarn-restore-cache
    name: Restore Yarn Artifact Cache
    keys:
      - v1-yarn-{{ arch }}-{{ checksum "package.json" }}
      - v1-yarn-{{ arch }}-

  - &yarn-save-cache
    name: Save Yarn Artifact Cache
    paths:
      - node_modules
      - ~/.cache/yarn
    key: v1-yarn-{{ arch }}-{{ checksum "package.json" }}

  - &yarn
    |
      yarn install --non-interactive --cache-folder ~/.cache/yarn

defaults: &defaults
  working_directory: ~/podlove-web-player

defaults-js: &defaults-js
  <<: *defaults
  docker:
    - image: circleci/node:8
  environment:
    - PATH: "/opt/yarn/yarn-v1.5.1/bin:/home/circleci/.yarn/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

defaults-cypress: &defaults-cypress
  <<: *defaults
  docker:
    - image: cypress/base:8
  environment:
    - TERM: xterm
    - PATH: "/opt/yarn/yarn-v1.5.1/bin:/home/circleci/.yarn/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

jobs:
  checkout:
    <<: *defaults-js
    name: Checkout Project
    steps:
      - checkout
      - run: *setup-artifacts
      - persist_to_workspace:
          root: .
          paths: .

  install:
    <<: *defaults-js
    name: Install Project Dependencies
    steps:
      - attach_workspace:
          at: ~/podlove-web-player
      - restore-cache: *yarn-restore-cache
      - run: node --version
      - run: npm --version
      - run: yarn --version
      - run: yarn global add greenkeeper-lockfile@1
      - run: greenkeeper-lockfile-update
      - run: *yarn
      - save-cache: *yarn-save-cache
      - persist_to_workspace:
          root: .
          paths: .

  docs-dev:
    <<: *defaults-js
    name: Generating Documentation
    steps:
      - attach_workspace:
          at: ~/podlove-web-player
      - restore-cache: *yarn-restore-cache

      - run: yarn docs:prod

      - save-cache: *yarn-save-cache
      - persist_to_workspace:
          root: .
          paths: .

  docs-prod:
    <<: *defaults-js
    name: Generating Documentation
    steps:
      - attach_workspace:
          at: ~/podlove-web-player
      - restore-cache: *yarn-restore-cache

      - run: BASE=podlove-web-player/ yarn docs:prod

      - save-cache: *yarn-save-cache
      - persist_to_workspace:
          root: .
          paths: .

  build-dev:
    <<: *defaults-js
    name: Building Project
    steps:
      - attach_workspace:
          at: ~/podlove-web-player
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: .

  build-prod:
    <<: *defaults-js
    name: Building Project
    steps:
      - attach_workspace:
          at: ~/podlove-web-player
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: .

  test-lint:
    <<: *defaults-js
    name: Linting Project
    steps:
      - attach_workspace:
          at: ~/podlove-web-player
      - run: yarn lint:ci
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports

  test-unit:
    <<: *defaults-js
    name: Unit Tests
    steps:
      - attach_workspace:
          at: ~/podlove-web-player
      - run: yarn test:ci
      - run: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: reports
      - store_artifacts:
          path: coverage/lcov-report

  test-build:
    <<: *defaults-js
    name: Unit Tests
    steps:
      - attach_workspace:
          at: ~/podlove-web-player
      - run: yarn build

  test-integration:
    <<: *defaults-cypress
    name: Integration Tests
    steps:
      - attach_workspace:
          at: ~/podlove-web-player
      - run: yarn test:integration
      - store_test_results:
          path: reports
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

  greenkeeper:
    <<: *defaults-js
    name: Updating Greenkeeper Lockfile
    steps:
      - attach_workspace:
          at: ~/podlove-web-player
      - restore-cache: *yarn-restore-cache
      - run: yarn global add greenkeeper-lockfile@1
      - run: greenkeeper-lockfile-upload

  deploy-staging:
    <<: *defaults-js
    name: Deploying to podlove-player.surge.sh
    steps:
      - attach_workspace:
          at: ~/podlove-web-player
      - restore-cache: *yarn-restore-cache
      - run: yarn deploy:surge

  deploy-production:
    <<: *defaults-js
    name: Deploying to docs.podlove.org/podlove-web-player
    steps:
      - attach_workspace:
          at: ~/podlove-web-player
      - restore-cache: *yarn-restore-cache
      - checkout
      - run: yarn deploy:gh-pages

  publish-npm:
    <<: *defaults-js
    name: Publish npm package
    steps:
      - attach_workspace:
          at: ~/podlove-web-player
      - restore-cache: *yarn-restore-cache
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn dist:clean
      - run: yarn build
      - run: npm publish

  publish-cdn:
    <<: *defaults-js
    name: Publish to cdn.podlove.org
    steps:
      - attach_workspace:
          at: ~/podlove-web-player
      - restore-cache: *yarn-restore-cache
      - run: sudo apt install rsync
      - run: mkdir -p ~/.ssh && ssh-keyscan rsync.keycdn.com >> ~/.ssh/known_hosts
      - run: yarn dist:clean
      - run: yarn build:cdn
      - run: yarn deploy:cdn

workflows:
  version: 2

  testing:
    jobs:
      - checkout
      - install:
          requires:
            - checkout

      # Tests
      - test-lint:
          requires:
            - install
      - test-unit:
          requires:
            - install
      - test-build:
          requires:
            - install
      - test-integration:
          requires:
            - install

      # Preview/Staging/Production Documentation Deployment
      - docs-dev:
          requires:
            - install
            - test-lint
            - test-unit
            - test-integration
            - test-build
          filters:
            branches:
              only:
                - /^(?!pull\/).*$/
                - development
              ignore: master
      - docs-prod:
          requires:
            - test-lint
            - test-unit
            - test-integration
            - test-build
          filters:
            branches:
              only: master
      - build-dev:
          requires:
            - docs-dev
          filters:
            branches:
              only: /^(?!pull\/).*$/
              ignore: master
      - build-prod:
          requires:
            - docs-prod
          filters:
            branches:
              only: master
      # Deploy to a commit hash prefixed surge env
      - deploy-preview:
          requires:
            - build-dev
          filters:
            branches:
              only: /^(?!pull\/).*$/
              ignore:
                - development
                - master
      # Deploy to podlove.surge.sh
      - deploy-staging:
          requires:
            - build-dev
          filters:
            branches:
              only: development
      # Deploy to podlove.org/podlove-web-player
      - deploy-production:
          requires:
            - build-prod
          filters:
            branches:
              only: master

      # Greenkeeper
      - greenkeeper:
          requires:
            - install
            - test-lint
            - test-unit
            - test-integration
            - test-build
          filters:
            branches:
              only: /^greenkeeper/.*$/

      # Publishing
      - publish-npm:
          requires:
            - test-lint
            - test-unit
            - test-integration
            - test-build
          filters:
            branches:
              only:
                - master
            tags:
              only: /v.*/

      - publish-cdn:
          requires:
            - test-lint
            - test-unit
            - test-integration
            - test-build
          filters:
            branches:
              only:
                - master
            tags:
              only: /v.*/
